[
{"type": "category", "text": "Sample Applications"},
{"type": "elem", "text": "ATW Desktop Check", "value": "ATWCheck"},
{"type": "elem", "text": "Vision", "value": "vision"},
{"type": "elem", "text": "IOBENCH", "value": "IObench"},
{"type": "elem", "text": "TOUR", "value": "Tour"},
{"type": "elem", "text": "Menu", "value": "Menu"},
{"type": "elem", "text": "C$COPY", "value": "ccopy"},
{"type": "elem", "text": "C$SYSTEM", "value": "CSystem"},
{"type": "elem", "text": "WIN$PRINTER - prndemox", "value": "prndemox"},
{"type": "elem", "text": "WIN$PRINTER - graphprn", "value": "graphprn"},
{"type": "elem", "text": "Paged Grid", "value": "PagedGrid"},
{"type": "elem", "text": "Grid Sorting", "value": "GridSorting"},
{"type": "elem", "text": "Library", "value": "Library"},
{"type": "elem", "text": "Message Box - Yes/No", "value": "YESNO"},
{"type": "elem", "text": "Web Browser", "value": "browser"},
{"type": "elem", "text": "Maps", "value": "maps"},
{"type": "elem", "text": "Email", "value": "mail"},
{"type": "elem", "text": "Terminal Info", "value": "TermInfo"},
{"type": "elem", "text": "F1 Terminate", "value": "terminate"},
{"type": "elem", "text": "Wheel Event", "value": "wheelevent"},
{"type": "category", "text": "ATM SQL Project"},
{"type": "elem", "text": "Maintenance", "value": "maintenance"},
{"type": "elem", "text": "ATM", "value": "atm"}
]
