### GENERAL
acurcl = "127.0.0.1"
acurcl_port = 5632
webserver_port = 3000
tcp_port = 8000
public_root_dir = "./Web"
file_cache = "./Web/cache"
path_fill_combo = "/home/support/AcuSupport/etc/fillcombo.js"
append_log_file = false
timeout_atw_conn = 2500
probing_connection = 10000

# enable_rsa_enc = false
# path_custom_js = "/home/support/AcuSupport/etc/customJSFunctionality.js"
# reconnect_interval = 1000
# max_reconnect_interval = 30000
# reconnect_decay = 1
# timeout_interval = 200000
# max_reconnect_attempts = 30
# path_resources = "/AcuResources"

### PROTOCOL
authorized_access = false
handshake_timeout = 3
ws_compression = true
max_pkg_size = 64000

### LOG
log_level = 15
logfile = "/home/support/AcuSupport/etc/logs/gateway.log"

### SSL
use_ssl = false
ssl_key_file = "/home/support/AcuSupport/etc/SSL/server.key"
ssl_crt_file = "/home/support/AcuSupport/etc/SSL/server.crt"

# [custom_return]
# DEFAULT = "https://www.microfocus.com"
# MY_ALIAS = "https://www.google.com"

# [customize_css]
# Example1 = "./Web/_CSS/examples/defaultCustomCSS.css"
# FX = "./Web/_CSS/examples/ThemeFX.css"