# AcuConnect host
# acurcl	127.0.0.1

# AcuConnect port
# acurcl_port	5632
acurcl_port	1020

# Use SSL
# use_ssl	0

# SSL Key File
# ssl_key_file	

# SSL Certification File
# ssl_cert_file	

# Max Packet Size
# max_pkg_size	64000

# Log Level (1, 2, 4, or 8)
# log_level	0
log_level	1

# Log filename
# logfile	C:\etc\log\gateway.log

# TCP Port
# tcp_port	8008
tcp_port	8009

# Web Server Port
# webserver_port	3000

# Request Username/Password Always (0=false, 1=true)
# authorized_access	0

# Enables WebSocket compression (if supported)
# ws_compression	1

# Public Root Directory
# public_root_dir	.\Web
public_root_dir	./Web

# File Cache Directory
# file_cache	C:\tmp\Web\cache

# Handshake timeout (units: seconds)
# handshake_timeout	3

# Themes
# customize_css	theme=file
customize_css	10-2="./Web/_CSS/10-2-example.css "
customize_css	Fall=./Web/_CSS/ThemeFall.css
customize_css	10-2-example=C:\AcuSamples\CSS\10-2-example.css
customize_css	Harvest=C:\AcuSamples\CSS\Harvest.css
